/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface File {
  id: Generated<string>;
  name: string;
  path: string;
  size: string;
  type: string;
  updated_at: Generated<Timestamp>;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string;
}

export interface User {
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  id: Generated<string>;
  last_name: string;
  password: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  file: File;
  user: User;
}
